/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as CourseIndexRouteImport } from './routes/course.index'
import { Route as SalesSettingsRouteImport } from './routes/sales.settings'
import { Route as SalesReportsRouteImport } from './routes/sales.reports'
import { Route as SalesLoginRouteImport } from './routes/sales.login'
import { Route as SalesLeadsRouteImport } from './routes/sales.leads'
import { Route as SalesExpensesRouteImport } from './routes/sales.expenses'
import { Route as SalesCoursesRouteImport } from './routes/sales.courses'
import { Route as SalesAccountingRouteImport } from './routes/sales.accounting'
import { Route as CourseResetPasswordRouteImport } from './routes/course.reset-password'
import { Route as CourseRegisterRouteImport } from './routes/course.register'
import { Route as CourseProfileRouteImport } from './routes/course.profile'
import { Route as CourseLoginRouteImport } from './routes/course.login'
import { Route as CourseForgotPasswordRouteImport } from './routes/course.forgot-password'
import { Route as CourseAdminRouteImport } from './routes/course.admin'
import { Route as CourseAdminIndexRouteImport } from './routes/course.admin.index'
import { Route as SalesLeadsIdRouteImport } from './routes/sales.leads.$id'
import { Route as CourseCourseCourseIdRouteImport } from './routes/course.course.$courseId'
import { Route as CourseAdminTeachersRouteImport } from './routes/course.admin.teachers'
import { Route as CourseAdminStudentsRouteImport } from './routes/course.admin.students'
import { Route as CourseAdminPendingRouteImport } from './routes/course.admin.pending'
import { Route as CourseAdminCoursesRouteImport } from './routes/course.admin.courses'
import { Route as CourseAdminStudentUserIdRouteImport } from './routes/course.admin.student.$userId'
import { Route as CourseAdminCourseCourseIdRouteImport } from './routes/course.admin.course.$courseId'
import { Route as CourseCourseCourseIdVideoVideoIdRouteImport } from './routes/course.course.$courseId.video.$videoId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesRoute,
} as any)
const CourseIndexRoute = CourseIndexRouteImport.update({
  id: '/course/',
  path: '/course/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesSettingsRoute = SalesSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SalesRoute,
} as any)
const SalesReportsRoute = SalesReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SalesRoute,
} as any)
const SalesLoginRoute = SalesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SalesRoute,
} as any)
const SalesLeadsRoute = SalesLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => SalesRoute,
} as any)
const SalesExpensesRoute = SalesExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => SalesRoute,
} as any)
const SalesCoursesRoute = SalesCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => SalesRoute,
} as any)
const SalesAccountingRoute = SalesAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => SalesRoute,
} as any)
const CourseResetPasswordRoute = CourseResetPasswordRouteImport.update({
  id: '/course/reset-password',
  path: '/course/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRegisterRoute = CourseRegisterRouteImport.update({
  id: '/course/register',
  path: '/course/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseProfileRoute = CourseProfileRouteImport.update({
  id: '/course/profile',
  path: '/course/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseLoginRoute = CourseLoginRouteImport.update({
  id: '/course/login',
  path: '/course/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseForgotPasswordRoute = CourseForgotPasswordRouteImport.update({
  id: '/course/forgot-password',
  path: '/course/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseAdminRoute = CourseAdminRouteImport.update({
  id: '/course/admin',
  path: '/course/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseAdminIndexRoute = CourseAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CourseAdminRoute,
} as any)
const SalesLeadsIdRoute = SalesLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalesLeadsRoute,
} as any)
const CourseCourseCourseIdRoute = CourseCourseCourseIdRouteImport.update({
  id: '/course/course/$courseId',
  path: '/course/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseAdminTeachersRoute = CourseAdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => CourseAdminRoute,
} as any)
const CourseAdminStudentsRoute = CourseAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => CourseAdminRoute,
} as any)
const CourseAdminPendingRoute = CourseAdminPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => CourseAdminRoute,
} as any)
const CourseAdminCoursesRoute = CourseAdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => CourseAdminRoute,
} as any)
const CourseAdminStudentUserIdRoute =
  CourseAdminStudentUserIdRouteImport.update({
    id: '/student/$userId',
    path: '/student/$userId',
    getParentRoute: () => CourseAdminRoute,
  } as any)
const CourseAdminCourseCourseIdRoute =
  CourseAdminCourseCourseIdRouteImport.update({
    id: '/course/$courseId',
    path: '/course/$courseId',
    getParentRoute: () => CourseAdminRoute,
  } as any)
const CourseCourseCourseIdVideoVideoIdRoute =
  CourseCourseCourseIdVideoVideoIdRouteImport.update({
    id: '/video/$videoId',
    path: '/video/$videoId',
    getParentRoute: () => CourseCourseCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sales': typeof SalesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/course/admin': typeof CourseAdminRouteWithChildren
  '/course/forgot-password': typeof CourseForgotPasswordRoute
  '/course/login': typeof CourseLoginRoute
  '/course/profile': typeof CourseProfileRoute
  '/course/register': typeof CourseRegisterRoute
  '/course/reset-password': typeof CourseResetPasswordRoute
  '/sales/accounting': typeof SalesAccountingRoute
  '/sales/courses': typeof SalesCoursesRoute
  '/sales/expenses': typeof SalesExpensesRoute
  '/sales/leads': typeof SalesLeadsRouteWithChildren
  '/sales/login': typeof SalesLoginRoute
  '/sales/reports': typeof SalesReportsRoute
  '/sales/settings': typeof SalesSettingsRoute
  '/course/': typeof CourseIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/course/admin/courses': typeof CourseAdminCoursesRoute
  '/course/admin/pending': typeof CourseAdminPendingRoute
  '/course/admin/students': typeof CourseAdminStudentsRoute
  '/course/admin/teachers': typeof CourseAdminTeachersRoute
  '/course/course/$courseId': typeof CourseCourseCourseIdRouteWithChildren
  '/sales/leads/$id': typeof SalesLeadsIdRoute
  '/course/admin/': typeof CourseAdminIndexRoute
  '/course/admin/course/$courseId': typeof CourseAdminCourseCourseIdRoute
  '/course/admin/student/$userId': typeof CourseAdminStudentUserIdRoute
  '/course/course/$courseId/video/$videoId': typeof CourseCourseCourseIdVideoVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/course/forgot-password': typeof CourseForgotPasswordRoute
  '/course/login': typeof CourseLoginRoute
  '/course/profile': typeof CourseProfileRoute
  '/course/register': typeof CourseRegisterRoute
  '/course/reset-password': typeof CourseResetPasswordRoute
  '/sales/accounting': typeof SalesAccountingRoute
  '/sales/courses': typeof SalesCoursesRoute
  '/sales/expenses': typeof SalesExpensesRoute
  '/sales/leads': typeof SalesLeadsRouteWithChildren
  '/sales/login': typeof SalesLoginRoute
  '/sales/reports': typeof SalesReportsRoute
  '/sales/settings': typeof SalesSettingsRoute
  '/course': typeof CourseIndexRoute
  '/sales': typeof SalesIndexRoute
  '/course/admin/courses': typeof CourseAdminCoursesRoute
  '/course/admin/pending': typeof CourseAdminPendingRoute
  '/course/admin/students': typeof CourseAdminStudentsRoute
  '/course/admin/teachers': typeof CourseAdminTeachersRoute
  '/course/course/$courseId': typeof CourseCourseCourseIdRouteWithChildren
  '/sales/leads/$id': typeof SalesLeadsIdRoute
  '/course/admin': typeof CourseAdminIndexRoute
  '/course/admin/course/$courseId': typeof CourseAdminCourseCourseIdRoute
  '/course/admin/student/$userId': typeof CourseAdminStudentUserIdRoute
  '/course/course/$courseId/video/$videoId': typeof CourseCourseCourseIdVideoVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sales': typeof SalesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/course/admin': typeof CourseAdminRouteWithChildren
  '/course/forgot-password': typeof CourseForgotPasswordRoute
  '/course/login': typeof CourseLoginRoute
  '/course/profile': typeof CourseProfileRoute
  '/course/register': typeof CourseRegisterRoute
  '/course/reset-password': typeof CourseResetPasswordRoute
  '/sales/accounting': typeof SalesAccountingRoute
  '/sales/courses': typeof SalesCoursesRoute
  '/sales/expenses': typeof SalesExpensesRoute
  '/sales/leads': typeof SalesLeadsRouteWithChildren
  '/sales/login': typeof SalesLoginRoute
  '/sales/reports': typeof SalesReportsRoute
  '/sales/settings': typeof SalesSettingsRoute
  '/course/': typeof CourseIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/course/admin/courses': typeof CourseAdminCoursesRoute
  '/course/admin/pending': typeof CourseAdminPendingRoute
  '/course/admin/students': typeof CourseAdminStudentsRoute
  '/course/admin/teachers': typeof CourseAdminTeachersRoute
  '/course/course/$courseId': typeof CourseCourseCourseIdRouteWithChildren
  '/sales/leads/$id': typeof SalesLeadsIdRoute
  '/course/admin/': typeof CourseAdminIndexRoute
  '/course/admin/course/$courseId': typeof CourseAdminCourseCourseIdRoute
  '/course/admin/student/$userId': typeof CourseAdminStudentUserIdRoute
  '/course/course/$courseId/video/$videoId': typeof CourseCourseCourseIdVideoVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sales'
    | '/sitemap.xml'
    | '/course/admin'
    | '/course/forgot-password'
    | '/course/login'
    | '/course/profile'
    | '/course/register'
    | '/course/reset-password'
    | '/sales/accounting'
    | '/sales/courses'
    | '/sales/expenses'
    | '/sales/leads'
    | '/sales/login'
    | '/sales/reports'
    | '/sales/settings'
    | '/course/'
    | '/sales/'
    | '/course/admin/courses'
    | '/course/admin/pending'
    | '/course/admin/students'
    | '/course/admin/teachers'
    | '/course/course/$courseId'
    | '/sales/leads/$id'
    | '/course/admin/'
    | '/course/admin/course/$courseId'
    | '/course/admin/student/$userId'
    | '/course/course/$courseId/video/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/course/forgot-password'
    | '/course/login'
    | '/course/profile'
    | '/course/register'
    | '/course/reset-password'
    | '/sales/accounting'
    | '/sales/courses'
    | '/sales/expenses'
    | '/sales/leads'
    | '/sales/login'
    | '/sales/reports'
    | '/sales/settings'
    | '/course'
    | '/sales'
    | '/course/admin/courses'
    | '/course/admin/pending'
    | '/course/admin/students'
    | '/course/admin/teachers'
    | '/course/course/$courseId'
    | '/sales/leads/$id'
    | '/course/admin'
    | '/course/admin/course/$courseId'
    | '/course/admin/student/$userId'
    | '/course/course/$courseId/video/$videoId'
  id:
    | '__root__'
    | '/'
    | '/sales'
    | '/sitemap.xml'
    | '/course/admin'
    | '/course/forgot-password'
    | '/course/login'
    | '/course/profile'
    | '/course/register'
    | '/course/reset-password'
    | '/sales/accounting'
    | '/sales/courses'
    | '/sales/expenses'
    | '/sales/leads'
    | '/sales/login'
    | '/sales/reports'
    | '/sales/settings'
    | '/course/'
    | '/sales/'
    | '/course/admin/courses'
    | '/course/admin/pending'
    | '/course/admin/students'
    | '/course/admin/teachers'
    | '/course/course/$courseId'
    | '/sales/leads/$id'
    | '/course/admin/'
    | '/course/admin/course/$courseId'
    | '/course/admin/student/$userId'
    | '/course/course/$courseId/video/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SalesRoute: typeof SalesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CourseAdminRoute: typeof CourseAdminRouteWithChildren
  CourseForgotPasswordRoute: typeof CourseForgotPasswordRoute
  CourseLoginRoute: typeof CourseLoginRoute
  CourseProfileRoute: typeof CourseProfileRoute
  CourseRegisterRoute: typeof CourseRegisterRoute
  CourseResetPasswordRoute: typeof CourseResetPasswordRoute
  CourseIndexRoute: typeof CourseIndexRoute
  CourseCourseCourseIdRoute: typeof CourseCourseCourseIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof SalesRoute
    }
    '/course/': {
      id: '/course/'
      path: '/course'
      fullPath: '/course/'
      preLoaderRoute: typeof CourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/settings': {
      id: '/sales/settings'
      path: '/settings'
      fullPath: '/sales/settings'
      preLoaderRoute: typeof SalesSettingsRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/reports': {
      id: '/sales/reports'
      path: '/reports'
      fullPath: '/sales/reports'
      preLoaderRoute: typeof SalesReportsRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/login': {
      id: '/sales/login'
      path: '/login'
      fullPath: '/sales/login'
      preLoaderRoute: typeof SalesLoginRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/leads': {
      id: '/sales/leads'
      path: '/leads'
      fullPath: '/sales/leads'
      preLoaderRoute: typeof SalesLeadsRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/expenses': {
      id: '/sales/expenses'
      path: '/expenses'
      fullPath: '/sales/expenses'
      preLoaderRoute: typeof SalesExpensesRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/courses': {
      id: '/sales/courses'
      path: '/courses'
      fullPath: '/sales/courses'
      preLoaderRoute: typeof SalesCoursesRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/accounting': {
      id: '/sales/accounting'
      path: '/accounting'
      fullPath: '/sales/accounting'
      preLoaderRoute: typeof SalesAccountingRouteImport
      parentRoute: typeof SalesRoute
    }
    '/course/reset-password': {
      id: '/course/reset-password'
      path: '/course/reset-password'
      fullPath: '/course/reset-password'
      preLoaderRoute: typeof CourseResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/register': {
      id: '/course/register'
      path: '/course/register'
      fullPath: '/course/register'
      preLoaderRoute: typeof CourseRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/profile': {
      id: '/course/profile'
      path: '/course/profile'
      fullPath: '/course/profile'
      preLoaderRoute: typeof CourseProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/login': {
      id: '/course/login'
      path: '/course/login'
      fullPath: '/course/login'
      preLoaderRoute: typeof CourseLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/forgot-password': {
      id: '/course/forgot-password'
      path: '/course/forgot-password'
      fullPath: '/course/forgot-password'
      preLoaderRoute: typeof CourseForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/admin': {
      id: '/course/admin'
      path: '/course/admin'
      fullPath: '/course/admin'
      preLoaderRoute: typeof CourseAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/admin/': {
      id: '/course/admin/'
      path: '/'
      fullPath: '/course/admin/'
      preLoaderRoute: typeof CourseAdminIndexRouteImport
      parentRoute: typeof CourseAdminRoute
    }
    '/sales/leads/$id': {
      id: '/sales/leads/$id'
      path: '/$id'
      fullPath: '/sales/leads/$id'
      preLoaderRoute: typeof SalesLeadsIdRouteImport
      parentRoute: typeof SalesLeadsRoute
    }
    '/course/course/$courseId': {
      id: '/course/course/$courseId'
      path: '/course/course/$courseId'
      fullPath: '/course/course/$courseId'
      preLoaderRoute: typeof CourseCourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/admin/teachers': {
      id: '/course/admin/teachers'
      path: '/teachers'
      fullPath: '/course/admin/teachers'
      preLoaderRoute: typeof CourseAdminTeachersRouteImport
      parentRoute: typeof CourseAdminRoute
    }
    '/course/admin/students': {
      id: '/course/admin/students'
      path: '/students'
      fullPath: '/course/admin/students'
      preLoaderRoute: typeof CourseAdminStudentsRouteImport
      parentRoute: typeof CourseAdminRoute
    }
    '/course/admin/pending': {
      id: '/course/admin/pending'
      path: '/pending'
      fullPath: '/course/admin/pending'
      preLoaderRoute: typeof CourseAdminPendingRouteImport
      parentRoute: typeof CourseAdminRoute
    }
    '/course/admin/courses': {
      id: '/course/admin/courses'
      path: '/courses'
      fullPath: '/course/admin/courses'
      preLoaderRoute: typeof CourseAdminCoursesRouteImport
      parentRoute: typeof CourseAdminRoute
    }
    '/course/admin/student/$userId': {
      id: '/course/admin/student/$userId'
      path: '/student/$userId'
      fullPath: '/course/admin/student/$userId'
      preLoaderRoute: typeof CourseAdminStudentUserIdRouteImport
      parentRoute: typeof CourseAdminRoute
    }
    '/course/admin/course/$courseId': {
      id: '/course/admin/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/admin/course/$courseId'
      preLoaderRoute: typeof CourseAdminCourseCourseIdRouteImport
      parentRoute: typeof CourseAdminRoute
    }
    '/course/course/$courseId/video/$videoId': {
      id: '/course/course/$courseId/video/$videoId'
      path: '/video/$videoId'
      fullPath: '/course/course/$courseId/video/$videoId'
      preLoaderRoute: typeof CourseCourseCourseIdVideoVideoIdRouteImport
      parentRoute: typeof CourseCourseCourseIdRoute
    }
  }
}

interface SalesLeadsRouteChildren {
  SalesLeadsIdRoute: typeof SalesLeadsIdRoute
}

const SalesLeadsRouteChildren: SalesLeadsRouteChildren = {
  SalesLeadsIdRoute: SalesLeadsIdRoute,
}

const SalesLeadsRouteWithChildren = SalesLeadsRoute._addFileChildren(
  SalesLeadsRouteChildren,
)

interface SalesRouteChildren {
  SalesAccountingRoute: typeof SalesAccountingRoute
  SalesCoursesRoute: typeof SalesCoursesRoute
  SalesExpensesRoute: typeof SalesExpensesRoute
  SalesLeadsRoute: typeof SalesLeadsRouteWithChildren
  SalesLoginRoute: typeof SalesLoginRoute
  SalesReportsRoute: typeof SalesReportsRoute
  SalesSettingsRoute: typeof SalesSettingsRoute
  SalesIndexRoute: typeof SalesIndexRoute
}

const SalesRouteChildren: SalesRouteChildren = {
  SalesAccountingRoute: SalesAccountingRoute,
  SalesCoursesRoute: SalesCoursesRoute,
  SalesExpensesRoute: SalesExpensesRoute,
  SalesLeadsRoute: SalesLeadsRouteWithChildren,
  SalesLoginRoute: SalesLoginRoute,
  SalesReportsRoute: SalesReportsRoute,
  SalesSettingsRoute: SalesSettingsRoute,
  SalesIndexRoute: SalesIndexRoute,
}

const SalesRouteWithChildren = SalesRoute._addFileChildren(SalesRouteChildren)

interface CourseAdminRouteChildren {
  CourseAdminCoursesRoute: typeof CourseAdminCoursesRoute
  CourseAdminPendingRoute: typeof CourseAdminPendingRoute
  CourseAdminStudentsRoute: typeof CourseAdminStudentsRoute
  CourseAdminTeachersRoute: typeof CourseAdminTeachersRoute
  CourseAdminIndexRoute: typeof CourseAdminIndexRoute
  CourseAdminCourseCourseIdRoute: typeof CourseAdminCourseCourseIdRoute
  CourseAdminStudentUserIdRoute: typeof CourseAdminStudentUserIdRoute
}

const CourseAdminRouteChildren: CourseAdminRouteChildren = {
  CourseAdminCoursesRoute: CourseAdminCoursesRoute,
  CourseAdminPendingRoute: CourseAdminPendingRoute,
  CourseAdminStudentsRoute: CourseAdminStudentsRoute,
  CourseAdminTeachersRoute: CourseAdminTeachersRoute,
  CourseAdminIndexRoute: CourseAdminIndexRoute,
  CourseAdminCourseCourseIdRoute: CourseAdminCourseCourseIdRoute,
  CourseAdminStudentUserIdRoute: CourseAdminStudentUserIdRoute,
}

const CourseAdminRouteWithChildren = CourseAdminRoute._addFileChildren(
  CourseAdminRouteChildren,
)

interface CourseCourseCourseIdRouteChildren {
  CourseCourseCourseIdVideoVideoIdRoute: typeof CourseCourseCourseIdVideoVideoIdRoute
}

const CourseCourseCourseIdRouteChildren: CourseCourseCourseIdRouteChildren = {
  CourseCourseCourseIdVideoVideoIdRoute: CourseCourseCourseIdVideoVideoIdRoute,
}

const CourseCourseCourseIdRouteWithChildren =
  CourseCourseCourseIdRoute._addFileChildren(CourseCourseCourseIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SalesRoute: SalesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CourseAdminRoute: CourseAdminRouteWithChildren,
  CourseForgotPasswordRoute: CourseForgotPasswordRoute,
  CourseLoginRoute: CourseLoginRoute,
  CourseProfileRoute: CourseProfileRoute,
  CourseRegisterRoute: CourseRegisterRoute,
  CourseResetPasswordRoute: CourseResetPasswordRoute,
  CourseIndexRoute: CourseIndexRoute,
  CourseCourseCourseIdRoute: CourseCourseCourseIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
