/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AllCoursesRouteImport } from './routes/all-courses'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as SalesSettingsRouteImport } from './routes/sales.settings'
import { Route as SalesReportsRouteImport } from './routes/sales.reports'
import { Route as SalesLoginRouteImport } from './routes/sales.login'
import { Route as SalesLeadsRouteImport } from './routes/sales.leads'
import { Route as SalesExpensesRouteImport } from './routes/sales.expenses'
import { Route as SalesCoursesRouteImport } from './routes/sales.courses'
import { Route as SalesAccountingRouteImport } from './routes/sales.accounting'
import { Route as DashboardTeacherRouteImport } from './routes/dashboard.teacher'
import { Route as DashboardResetPasswordRouteImport } from './routes/dashboard.reset-password'
import { Route as DashboardRegisterRouteImport } from './routes/dashboard.register'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardMyCourseRouteImport } from './routes/dashboard.my-course'
import { Route as DashboardManagerRouteImport } from './routes/dashboard.manager'
import { Route as DashboardLoginRouteImport } from './routes/dashboard.login'
import { Route as DashboardLiveClassRouteImport } from './routes/dashboard.live-class'
import { Route as DashboardForgotPasswordRouteImport } from './routes/dashboard.forgot-password'
import { Route as DashboardEbookRouteImport } from './routes/dashboard.ebook'
import { Route as DashboardCertificateRouteImport } from './routes/dashboard.certificate'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardTeacherIndexRouteImport } from './routes/dashboard.teacher.index'
import { Route as DashboardManagerIndexRouteImport } from './routes/dashboard.manager.index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as SalesLeadsIdRouteImport } from './routes/sales.leads.$id'
import { Route as DashboardTeacherSessionsRouteImport } from './routes/dashboard.teacher.sessions'
import { Route as DashboardManagerStudentsRouteImport } from './routes/dashboard.manager.students'
import { Route as DashboardManagerSessionsRouteImport } from './routes/dashboard.manager.sessions'
import { Route as DashboardManagerCoursesRouteImport } from './routes/dashboard.manager.courses'
import { Route as DashboardManagerBatchesRouteImport } from './routes/dashboard.manager.batches'
import { Route as DashboardCourseCourseIdRouteImport } from './routes/dashboard.course.$courseId'
import { Route as DashboardAdminTeachersRouteImport } from './routes/dashboard.admin.teachers'
import { Route as DashboardAdminStudentsRouteImport } from './routes/dashboard.admin.students'
import { Route as DashboardAdminSessionsRouteImport } from './routes/dashboard.admin.sessions'
import { Route as DashboardAdminPendingRouteImport } from './routes/dashboard.admin.pending'
import { Route as DashboardAdminCoursesRouteImport } from './routes/dashboard.admin.courses'
import { Route as DashboardAdminStudentUserIdRouteImport } from './routes/dashboard.admin.student.$userId'
import { Route as DashboardAdminCourseCourseIdRouteImport } from './routes/dashboard.admin.course.$courseId'
import { Route as DashboardCourseCourseIdVideoVideoIdRouteImport } from './routes/dashboard.course.$courseId.video.$videoId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AllCoursesRoute = AllCoursesRouteImport.update({
  id: '/all-courses',
  path: '/all-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesSettingsRoute = SalesSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SalesRoute,
} as any)
const SalesReportsRoute = SalesReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SalesRoute,
} as any)
const SalesLoginRoute = SalesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SalesRoute,
} as any)
const SalesLeadsRoute = SalesLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => SalesRoute,
} as any)
const SalesExpensesRoute = SalesExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => SalesRoute,
} as any)
const SalesCoursesRoute = SalesCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => SalesRoute,
} as any)
const SalesAccountingRoute = SalesAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => SalesRoute,
} as any)
const DashboardTeacherRoute = DashboardTeacherRouteImport.update({
  id: '/dashboard/teacher',
  path: '/dashboard/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardResetPasswordRoute = DashboardResetPasswordRouteImport.update({
  id: '/dashboard/reset-password',
  path: '/dashboard/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRegisterRoute = DashboardRegisterRouteImport.update({
  id: '/dashboard/register',
  path: '/dashboard/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMyCourseRoute = DashboardMyCourseRouteImport.update({
  id: '/dashboard/my-course',
  path: '/dashboard/my-course',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardManagerRoute = DashboardManagerRouteImport.update({
  id: '/dashboard/manager',
  path: '/dashboard/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/dashboard/login',
  path: '/dashboard/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLiveClassRoute = DashboardLiveClassRouteImport.update({
  id: '/dashboard/live-class',
  path: '/dashboard/live-class',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardForgotPasswordRoute = DashboardForgotPasswordRouteImport.update({
  id: '/dashboard/forgot-password',
  path: '/dashboard/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEbookRoute = DashboardEbookRouteImport.update({
  id: '/dashboard/ebook',
  path: '/dashboard/ebook',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCertificateRoute = DashboardCertificateRouteImport.update({
  id: '/dashboard/certificate',
  path: '/dashboard/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/dashboard/billing',
  path: '/dashboard/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeacherIndexRoute = DashboardTeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTeacherRoute,
} as any)
const DashboardManagerIndexRoute = DashboardManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardManagerRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const SalesLeadsIdRoute = SalesLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalesLeadsRoute,
} as any)
const DashboardTeacherSessionsRoute =
  DashboardTeacherSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => DashboardTeacherRoute,
  } as any)
const DashboardManagerStudentsRoute =
  DashboardManagerStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => DashboardManagerRoute,
  } as any)
const DashboardManagerSessionsRoute =
  DashboardManagerSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => DashboardManagerRoute,
  } as any)
const DashboardManagerCoursesRoute = DashboardManagerCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardManagerRoute,
} as any)
const DashboardManagerBatchesRoute = DashboardManagerBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => DashboardManagerRoute,
} as any)
const DashboardCourseCourseIdRoute = DashboardCourseCourseIdRouteImport.update({
  id: '/dashboard/course/$courseId',
  path: '/dashboard/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminTeachersRoute = DashboardAdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminStudentsRoute = DashboardAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSessionsRoute = DashboardAdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminPendingRoute = DashboardAdminPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminCoursesRoute = DashboardAdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminStudentUserIdRoute =
  DashboardAdminStudentUserIdRouteImport.update({
    id: '/student/$userId',
    path: '/student/$userId',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminCourseCourseIdRoute =
  DashboardAdminCourseCourseIdRouteImport.update({
    id: '/course/$courseId',
    path: '/course/$courseId',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardCourseCourseIdVideoVideoIdRoute =
  DashboardCourseCourseIdVideoVideoIdRouteImport.update({
    id: '/video/$videoId',
    path: '/video/$videoId',
    getParentRoute: () => DashboardCourseCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/all-courses': typeof AllCoursesRoute
  '/blog': typeof BlogRoute
  '/contact-us': typeof ContactUsRoute
  '/sales': typeof SalesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/certificate': typeof DashboardCertificateRoute
  '/dashboard/ebook': typeof DashboardEbookRoute
  '/dashboard/forgot-password': typeof DashboardForgotPasswordRoute
  '/dashboard/live-class': typeof DashboardLiveClassRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/manager': typeof DashboardManagerRouteWithChildren
  '/dashboard/my-course': typeof DashboardMyCourseRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/register': typeof DashboardRegisterRoute
  '/dashboard/reset-password': typeof DashboardResetPasswordRoute
  '/dashboard/teacher': typeof DashboardTeacherRouteWithChildren
  '/sales/accounting': typeof SalesAccountingRoute
  '/sales/courses': typeof SalesCoursesRoute
  '/sales/expenses': typeof SalesExpensesRoute
  '/sales/leads': typeof SalesLeadsRouteWithChildren
  '/sales/login': typeof SalesLoginRoute
  '/sales/reports': typeof SalesReportsRoute
  '/sales/settings': typeof SalesSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/dashboard/admin/courses': typeof DashboardAdminCoursesRoute
  '/dashboard/admin/pending': typeof DashboardAdminPendingRoute
  '/dashboard/admin/sessions': typeof DashboardAdminSessionsRoute
  '/dashboard/admin/students': typeof DashboardAdminStudentsRoute
  '/dashboard/admin/teachers': typeof DashboardAdminTeachersRoute
  '/dashboard/course/$courseId': typeof DashboardCourseCourseIdRouteWithChildren
  '/dashboard/manager/batches': typeof DashboardManagerBatchesRoute
  '/dashboard/manager/courses': typeof DashboardManagerCoursesRoute
  '/dashboard/manager/sessions': typeof DashboardManagerSessionsRoute
  '/dashboard/manager/students': typeof DashboardManagerStudentsRoute
  '/dashboard/teacher/sessions': typeof DashboardTeacherSessionsRoute
  '/sales/leads/$id': typeof SalesLeadsIdRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/manager/': typeof DashboardManagerIndexRoute
  '/dashboard/teacher/': typeof DashboardTeacherIndexRoute
  '/dashboard/admin/course/$courseId': typeof DashboardAdminCourseCourseIdRoute
  '/dashboard/admin/student/$userId': typeof DashboardAdminStudentUserIdRoute
  '/dashboard/course/$courseId/video/$videoId': typeof DashboardCourseCourseIdVideoVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/all-courses': typeof AllCoursesRoute
  '/blog': typeof BlogRoute
  '/contact-us': typeof ContactUsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/certificate': typeof DashboardCertificateRoute
  '/dashboard/ebook': typeof DashboardEbookRoute
  '/dashboard/forgot-password': typeof DashboardForgotPasswordRoute
  '/dashboard/live-class': typeof DashboardLiveClassRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/my-course': typeof DashboardMyCourseRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/register': typeof DashboardRegisterRoute
  '/dashboard/reset-password': typeof DashboardResetPasswordRoute
  '/sales/accounting': typeof SalesAccountingRoute
  '/sales/courses': typeof SalesCoursesRoute
  '/sales/expenses': typeof SalesExpensesRoute
  '/sales/leads': typeof SalesLeadsRouteWithChildren
  '/sales/login': typeof SalesLoginRoute
  '/sales/reports': typeof SalesReportsRoute
  '/sales/settings': typeof SalesSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/sales': typeof SalesIndexRoute
  '/dashboard/admin/courses': typeof DashboardAdminCoursesRoute
  '/dashboard/admin/pending': typeof DashboardAdminPendingRoute
  '/dashboard/admin/sessions': typeof DashboardAdminSessionsRoute
  '/dashboard/admin/students': typeof DashboardAdminStudentsRoute
  '/dashboard/admin/teachers': typeof DashboardAdminTeachersRoute
  '/dashboard/course/$courseId': typeof DashboardCourseCourseIdRouteWithChildren
  '/dashboard/manager/batches': typeof DashboardManagerBatchesRoute
  '/dashboard/manager/courses': typeof DashboardManagerCoursesRoute
  '/dashboard/manager/sessions': typeof DashboardManagerSessionsRoute
  '/dashboard/manager/students': typeof DashboardManagerStudentsRoute
  '/dashboard/teacher/sessions': typeof DashboardTeacherSessionsRoute
  '/sales/leads/$id': typeof SalesLeadsIdRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/manager': typeof DashboardManagerIndexRoute
  '/dashboard/teacher': typeof DashboardTeacherIndexRoute
  '/dashboard/admin/course/$courseId': typeof DashboardAdminCourseCourseIdRoute
  '/dashboard/admin/student/$userId': typeof DashboardAdminStudentUserIdRoute
  '/dashboard/course/$courseId/video/$videoId': typeof DashboardCourseCourseIdVideoVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/all-courses': typeof AllCoursesRoute
  '/blog': typeof BlogRoute
  '/contact-us': typeof ContactUsRoute
  '/sales': typeof SalesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/certificate': typeof DashboardCertificateRoute
  '/dashboard/ebook': typeof DashboardEbookRoute
  '/dashboard/forgot-password': typeof DashboardForgotPasswordRoute
  '/dashboard/live-class': typeof DashboardLiveClassRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/manager': typeof DashboardManagerRouteWithChildren
  '/dashboard/my-course': typeof DashboardMyCourseRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/register': typeof DashboardRegisterRoute
  '/dashboard/reset-password': typeof DashboardResetPasswordRoute
  '/dashboard/teacher': typeof DashboardTeacherRouteWithChildren
  '/sales/accounting': typeof SalesAccountingRoute
  '/sales/courses': typeof SalesCoursesRoute
  '/sales/expenses': typeof SalesExpensesRoute
  '/sales/leads': typeof SalesLeadsRouteWithChildren
  '/sales/login': typeof SalesLoginRoute
  '/sales/reports': typeof SalesReportsRoute
  '/sales/settings': typeof SalesSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/dashboard/admin/courses': typeof DashboardAdminCoursesRoute
  '/dashboard/admin/pending': typeof DashboardAdminPendingRoute
  '/dashboard/admin/sessions': typeof DashboardAdminSessionsRoute
  '/dashboard/admin/students': typeof DashboardAdminStudentsRoute
  '/dashboard/admin/teachers': typeof DashboardAdminTeachersRoute
  '/dashboard/course/$courseId': typeof DashboardCourseCourseIdRouteWithChildren
  '/dashboard/manager/batches': typeof DashboardManagerBatchesRoute
  '/dashboard/manager/courses': typeof DashboardManagerCoursesRoute
  '/dashboard/manager/sessions': typeof DashboardManagerSessionsRoute
  '/dashboard/manager/students': typeof DashboardManagerStudentsRoute
  '/dashboard/teacher/sessions': typeof DashboardTeacherSessionsRoute
  '/sales/leads/$id': typeof SalesLeadsIdRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/manager/': typeof DashboardManagerIndexRoute
  '/dashboard/teacher/': typeof DashboardTeacherIndexRoute
  '/dashboard/admin/course/$courseId': typeof DashboardAdminCourseCourseIdRoute
  '/dashboard/admin/student/$userId': typeof DashboardAdminStudentUserIdRoute
  '/dashboard/course/$courseId/video/$videoId': typeof DashboardCourseCourseIdVideoVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/all-courses'
    | '/blog'
    | '/contact-us'
    | '/sales'
    | '/sitemap.xml'
    | '/dashboard/admin'
    | '/dashboard/billing'
    | '/dashboard/certificate'
    | '/dashboard/ebook'
    | '/dashboard/forgot-password'
    | '/dashboard/live-class'
    | '/dashboard/login'
    | '/dashboard/manager'
    | '/dashboard/my-course'
    | '/dashboard/profile'
    | '/dashboard/register'
    | '/dashboard/reset-password'
    | '/dashboard/teacher'
    | '/sales/accounting'
    | '/sales/courses'
    | '/sales/expenses'
    | '/sales/leads'
    | '/sales/login'
    | '/sales/reports'
    | '/sales/settings'
    | '/dashboard/'
    | '/sales/'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/pending'
    | '/dashboard/admin/sessions'
    | '/dashboard/admin/students'
    | '/dashboard/admin/teachers'
    | '/dashboard/course/$courseId'
    | '/dashboard/manager/batches'
    | '/dashboard/manager/courses'
    | '/dashboard/manager/sessions'
    | '/dashboard/manager/students'
    | '/dashboard/teacher/sessions'
    | '/sales/leads/$id'
    | '/dashboard/admin/'
    | '/dashboard/manager/'
    | '/dashboard/teacher/'
    | '/dashboard/admin/course/$courseId'
    | '/dashboard/admin/student/$userId'
    | '/dashboard/course/$courseId/video/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/all-courses'
    | '/blog'
    | '/contact-us'
    | '/sitemap.xml'
    | '/dashboard/billing'
    | '/dashboard/certificate'
    | '/dashboard/ebook'
    | '/dashboard/forgot-password'
    | '/dashboard/live-class'
    | '/dashboard/login'
    | '/dashboard/my-course'
    | '/dashboard/profile'
    | '/dashboard/register'
    | '/dashboard/reset-password'
    | '/sales/accounting'
    | '/sales/courses'
    | '/sales/expenses'
    | '/sales/leads'
    | '/sales/login'
    | '/sales/reports'
    | '/sales/settings'
    | '/dashboard'
    | '/sales'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/pending'
    | '/dashboard/admin/sessions'
    | '/dashboard/admin/students'
    | '/dashboard/admin/teachers'
    | '/dashboard/course/$courseId'
    | '/dashboard/manager/batches'
    | '/dashboard/manager/courses'
    | '/dashboard/manager/sessions'
    | '/dashboard/manager/students'
    | '/dashboard/teacher/sessions'
    | '/sales/leads/$id'
    | '/dashboard/admin'
    | '/dashboard/manager'
    | '/dashboard/teacher'
    | '/dashboard/admin/course/$courseId'
    | '/dashboard/admin/student/$userId'
    | '/dashboard/course/$courseId/video/$videoId'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/all-courses'
    | '/blog'
    | '/contact-us'
    | '/sales'
    | '/sitemap.xml'
    | '/dashboard/admin'
    | '/dashboard/billing'
    | '/dashboard/certificate'
    | '/dashboard/ebook'
    | '/dashboard/forgot-password'
    | '/dashboard/live-class'
    | '/dashboard/login'
    | '/dashboard/manager'
    | '/dashboard/my-course'
    | '/dashboard/profile'
    | '/dashboard/register'
    | '/dashboard/reset-password'
    | '/dashboard/teacher'
    | '/sales/accounting'
    | '/sales/courses'
    | '/sales/expenses'
    | '/sales/leads'
    | '/sales/login'
    | '/sales/reports'
    | '/sales/settings'
    | '/dashboard/'
    | '/sales/'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/pending'
    | '/dashboard/admin/sessions'
    | '/dashboard/admin/students'
    | '/dashboard/admin/teachers'
    | '/dashboard/course/$courseId'
    | '/dashboard/manager/batches'
    | '/dashboard/manager/courses'
    | '/dashboard/manager/sessions'
    | '/dashboard/manager/students'
    | '/dashboard/teacher/sessions'
    | '/sales/leads/$id'
    | '/dashboard/admin/'
    | '/dashboard/manager/'
    | '/dashboard/teacher/'
    | '/dashboard/admin/course/$courseId'
    | '/dashboard/admin/student/$userId'
    | '/dashboard/course/$courseId/video/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AllCoursesRoute: typeof AllCoursesRoute
  BlogRoute: typeof BlogRoute
  ContactUsRoute: typeof ContactUsRoute
  SalesRoute: typeof SalesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardCertificateRoute: typeof DashboardCertificateRoute
  DashboardEbookRoute: typeof DashboardEbookRoute
  DashboardForgotPasswordRoute: typeof DashboardForgotPasswordRoute
  DashboardLiveClassRoute: typeof DashboardLiveClassRoute
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardManagerRoute: typeof DashboardManagerRouteWithChildren
  DashboardMyCourseRoute: typeof DashboardMyCourseRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRegisterRoute: typeof DashboardRegisterRoute
  DashboardResetPasswordRoute: typeof DashboardResetPasswordRoute
  DashboardTeacherRoute: typeof DashboardTeacherRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCourseCourseIdRoute: typeof DashboardCourseCourseIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-courses': {
      id: '/all-courses'
      path: '/all-courses'
      fullPath: '/all-courses'
      preLoaderRoute: typeof AllCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof SalesRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/settings': {
      id: '/sales/settings'
      path: '/settings'
      fullPath: '/sales/settings'
      preLoaderRoute: typeof SalesSettingsRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/reports': {
      id: '/sales/reports'
      path: '/reports'
      fullPath: '/sales/reports'
      preLoaderRoute: typeof SalesReportsRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/login': {
      id: '/sales/login'
      path: '/login'
      fullPath: '/sales/login'
      preLoaderRoute: typeof SalesLoginRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/leads': {
      id: '/sales/leads'
      path: '/leads'
      fullPath: '/sales/leads'
      preLoaderRoute: typeof SalesLeadsRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/expenses': {
      id: '/sales/expenses'
      path: '/expenses'
      fullPath: '/sales/expenses'
      preLoaderRoute: typeof SalesExpensesRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/courses': {
      id: '/sales/courses'
      path: '/courses'
      fullPath: '/sales/courses'
      preLoaderRoute: typeof SalesCoursesRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/accounting': {
      id: '/sales/accounting'
      path: '/accounting'
      fullPath: '/sales/accounting'
      preLoaderRoute: typeof SalesAccountingRouteImport
      parentRoute: typeof SalesRoute
    }
    '/dashboard/teacher': {
      id: '/dashboard/teacher'
      path: '/dashboard/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof DashboardTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reset-password': {
      id: '/dashboard/reset-password'
      path: '/dashboard/reset-password'
      fullPath: '/dashboard/reset-password'
      preLoaderRoute: typeof DashboardResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/register': {
      id: '/dashboard/register'
      path: '/dashboard/register'
      fullPath: '/dashboard/register'
      preLoaderRoute: typeof DashboardRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/my-course': {
      id: '/dashboard/my-course'
      path: '/dashboard/my-course'
      fullPath: '/dashboard/my-course'
      preLoaderRoute: typeof DashboardMyCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/manager': {
      id: '/dashboard/manager'
      path: '/dashboard/manager'
      fullPath: '/dashboard/manager'
      preLoaderRoute: typeof DashboardManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/dashboard/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/live-class': {
      id: '/dashboard/live-class'
      path: '/dashboard/live-class'
      fullPath: '/dashboard/live-class'
      preLoaderRoute: typeof DashboardLiveClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/forgot-password': {
      id: '/dashboard/forgot-password'
      path: '/dashboard/forgot-password'
      fullPath: '/dashboard/forgot-password'
      preLoaderRoute: typeof DashboardForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ebook': {
      id: '/dashboard/ebook'
      path: '/dashboard/ebook'
      fullPath: '/dashboard/ebook'
      preLoaderRoute: typeof DashboardEbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/certificate': {
      id: '/dashboard/certificate'
      path: '/dashboard/certificate'
      fullPath: '/dashboard/certificate'
      preLoaderRoute: typeof DashboardCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/dashboard/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/teacher/': {
      id: '/dashboard/teacher/'
      path: '/'
      fullPath: '/dashboard/teacher/'
      preLoaderRoute: typeof DashboardTeacherIndexRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/manager/': {
      id: '/dashboard/manager/'
      path: '/'
      fullPath: '/dashboard/manager/'
      preLoaderRoute: typeof DashboardManagerIndexRouteImport
      parentRoute: typeof DashboardManagerRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/sales/leads/$id': {
      id: '/sales/leads/$id'
      path: '/$id'
      fullPath: '/sales/leads/$id'
      preLoaderRoute: typeof SalesLeadsIdRouteImport
      parentRoute: typeof SalesLeadsRoute
    }
    '/dashboard/teacher/sessions': {
      id: '/dashboard/teacher/sessions'
      path: '/sessions'
      fullPath: '/dashboard/teacher/sessions'
      preLoaderRoute: typeof DashboardTeacherSessionsRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/manager/students': {
      id: '/dashboard/manager/students'
      path: '/students'
      fullPath: '/dashboard/manager/students'
      preLoaderRoute: typeof DashboardManagerStudentsRouteImport
      parentRoute: typeof DashboardManagerRoute
    }
    '/dashboard/manager/sessions': {
      id: '/dashboard/manager/sessions'
      path: '/sessions'
      fullPath: '/dashboard/manager/sessions'
      preLoaderRoute: typeof DashboardManagerSessionsRouteImport
      parentRoute: typeof DashboardManagerRoute
    }
    '/dashboard/manager/courses': {
      id: '/dashboard/manager/courses'
      path: '/courses'
      fullPath: '/dashboard/manager/courses'
      preLoaderRoute: typeof DashboardManagerCoursesRouteImport
      parentRoute: typeof DashboardManagerRoute
    }
    '/dashboard/manager/batches': {
      id: '/dashboard/manager/batches'
      path: '/batches'
      fullPath: '/dashboard/manager/batches'
      preLoaderRoute: typeof DashboardManagerBatchesRouteImport
      parentRoute: typeof DashboardManagerRoute
    }
    '/dashboard/course/$courseId': {
      id: '/dashboard/course/$courseId'
      path: '/dashboard/course/$courseId'
      fullPath: '/dashboard/course/$courseId'
      preLoaderRoute: typeof DashboardCourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/teachers': {
      id: '/dashboard/admin/teachers'
      path: '/teachers'
      fullPath: '/dashboard/admin/teachers'
      preLoaderRoute: typeof DashboardAdminTeachersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/students': {
      id: '/dashboard/admin/students'
      path: '/students'
      fullPath: '/dashboard/admin/students'
      preLoaderRoute: typeof DashboardAdminStudentsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/sessions': {
      id: '/dashboard/admin/sessions'
      path: '/sessions'
      fullPath: '/dashboard/admin/sessions'
      preLoaderRoute: typeof DashboardAdminSessionsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/pending': {
      id: '/dashboard/admin/pending'
      path: '/pending'
      fullPath: '/dashboard/admin/pending'
      preLoaderRoute: typeof DashboardAdminPendingRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/courses': {
      id: '/dashboard/admin/courses'
      path: '/courses'
      fullPath: '/dashboard/admin/courses'
      preLoaderRoute: typeof DashboardAdminCoursesRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/student/$userId': {
      id: '/dashboard/admin/student/$userId'
      path: '/student/$userId'
      fullPath: '/dashboard/admin/student/$userId'
      preLoaderRoute: typeof DashboardAdminStudentUserIdRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/course/$courseId': {
      id: '/dashboard/admin/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/dashboard/admin/course/$courseId'
      preLoaderRoute: typeof DashboardAdminCourseCourseIdRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/course/$courseId/video/$videoId': {
      id: '/dashboard/course/$courseId/video/$videoId'
      path: '/video/$videoId'
      fullPath: '/dashboard/course/$courseId/video/$videoId'
      preLoaderRoute: typeof DashboardCourseCourseIdVideoVideoIdRouteImport
      parentRoute: typeof DashboardCourseCourseIdRoute
    }
  }
}

interface SalesLeadsRouteChildren {
  SalesLeadsIdRoute: typeof SalesLeadsIdRoute
}

const SalesLeadsRouteChildren: SalesLeadsRouteChildren = {
  SalesLeadsIdRoute: SalesLeadsIdRoute,
}

const SalesLeadsRouteWithChildren = SalesLeadsRoute._addFileChildren(
  SalesLeadsRouteChildren,
)

interface SalesRouteChildren {
  SalesAccountingRoute: typeof SalesAccountingRoute
  SalesCoursesRoute: typeof SalesCoursesRoute
  SalesExpensesRoute: typeof SalesExpensesRoute
  SalesLeadsRoute: typeof SalesLeadsRouteWithChildren
  SalesLoginRoute: typeof SalesLoginRoute
  SalesReportsRoute: typeof SalesReportsRoute
  SalesSettingsRoute: typeof SalesSettingsRoute
  SalesIndexRoute: typeof SalesIndexRoute
}

const SalesRouteChildren: SalesRouteChildren = {
  SalesAccountingRoute: SalesAccountingRoute,
  SalesCoursesRoute: SalesCoursesRoute,
  SalesExpensesRoute: SalesExpensesRoute,
  SalesLeadsRoute: SalesLeadsRouteWithChildren,
  SalesLoginRoute: SalesLoginRoute,
  SalesReportsRoute: SalesReportsRoute,
  SalesSettingsRoute: SalesSettingsRoute,
  SalesIndexRoute: SalesIndexRoute,
}

const SalesRouteWithChildren = SalesRoute._addFileChildren(SalesRouteChildren)

interface DashboardAdminRouteChildren {
  DashboardAdminCoursesRoute: typeof DashboardAdminCoursesRoute
  DashboardAdminPendingRoute: typeof DashboardAdminPendingRoute
  DashboardAdminSessionsRoute: typeof DashboardAdminSessionsRoute
  DashboardAdminStudentsRoute: typeof DashboardAdminStudentsRoute
  DashboardAdminTeachersRoute: typeof DashboardAdminTeachersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardAdminCourseCourseIdRoute: typeof DashboardAdminCourseCourseIdRoute
  DashboardAdminStudentUserIdRoute: typeof DashboardAdminStudentUserIdRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminCoursesRoute: DashboardAdminCoursesRoute,
  DashboardAdminPendingRoute: DashboardAdminPendingRoute,
  DashboardAdminSessionsRoute: DashboardAdminSessionsRoute,
  DashboardAdminStudentsRoute: DashboardAdminStudentsRoute,
  DashboardAdminTeachersRoute: DashboardAdminTeachersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardAdminCourseCourseIdRoute: DashboardAdminCourseCourseIdRoute,
  DashboardAdminStudentUserIdRoute: DashboardAdminStudentUserIdRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardManagerRouteChildren {
  DashboardManagerBatchesRoute: typeof DashboardManagerBatchesRoute
  DashboardManagerCoursesRoute: typeof DashboardManagerCoursesRoute
  DashboardManagerSessionsRoute: typeof DashboardManagerSessionsRoute
  DashboardManagerStudentsRoute: typeof DashboardManagerStudentsRoute
  DashboardManagerIndexRoute: typeof DashboardManagerIndexRoute
}

const DashboardManagerRouteChildren: DashboardManagerRouteChildren = {
  DashboardManagerBatchesRoute: DashboardManagerBatchesRoute,
  DashboardManagerCoursesRoute: DashboardManagerCoursesRoute,
  DashboardManagerSessionsRoute: DashboardManagerSessionsRoute,
  DashboardManagerStudentsRoute: DashboardManagerStudentsRoute,
  DashboardManagerIndexRoute: DashboardManagerIndexRoute,
}

const DashboardManagerRouteWithChildren =
  DashboardManagerRoute._addFileChildren(DashboardManagerRouteChildren)

interface DashboardTeacherRouteChildren {
  DashboardTeacherSessionsRoute: typeof DashboardTeacherSessionsRoute
  DashboardTeacherIndexRoute: typeof DashboardTeacherIndexRoute
}

const DashboardTeacherRouteChildren: DashboardTeacherRouteChildren = {
  DashboardTeacherSessionsRoute: DashboardTeacherSessionsRoute,
  DashboardTeacherIndexRoute: DashboardTeacherIndexRoute,
}

const DashboardTeacherRouteWithChildren =
  DashboardTeacherRoute._addFileChildren(DashboardTeacherRouteChildren)

interface DashboardCourseCourseIdRouteChildren {
  DashboardCourseCourseIdVideoVideoIdRoute: typeof DashboardCourseCourseIdVideoVideoIdRoute
}

const DashboardCourseCourseIdRouteChildren: DashboardCourseCourseIdRouteChildren =
  {
    DashboardCourseCourseIdVideoVideoIdRoute:
      DashboardCourseCourseIdVideoVideoIdRoute,
  }

const DashboardCourseCourseIdRouteWithChildren =
  DashboardCourseCourseIdRoute._addFileChildren(
    DashboardCourseCourseIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AllCoursesRoute: AllCoursesRoute,
  BlogRoute: BlogRoute,
  ContactUsRoute: ContactUsRoute,
  SalesRoute: SalesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardCertificateRoute: DashboardCertificateRoute,
  DashboardEbookRoute: DashboardEbookRoute,
  DashboardForgotPasswordRoute: DashboardForgotPasswordRoute,
  DashboardLiveClassRoute: DashboardLiveClassRoute,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardManagerRoute: DashboardManagerRouteWithChildren,
  DashboardMyCourseRoute: DashboardMyCourseRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRegisterRoute: DashboardRegisterRoute,
  DashboardResetPasswordRoute: DashboardResetPasswordRoute,
  DashboardTeacherRoute: DashboardTeacherRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCourseCourseIdRoute: DashboardCourseCourseIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
